### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by yisraelU** [zio/zio-amqp#177]
Hi @svroonland  ,
Is there a feature list of potential ideas somewhere? I would love to take a crack at some and perhaps suggest some of my own .
I am coming from an Akka based amqp library (https://github.com/NewMotion/akka-rabbitmq) and I am trying to switch over to ZIO and not lose any features. 
Thanks

**Comment by svroonland** [comment]
That would be great. I don't have a feature list so much, but I'm sure there is quite some functionality that is not covered in the library yet so feel free to create issues and/or PRs. I'm on the ZIO discord as well if you want to discuss a bit more.
