### ISSUE TITLE
AMQPConfig default is invalid

### ISSUE THREAD

**Issue by Adriani-Furtado** [zio/zio-amqp#319]
When building the `AmqpUri` we are adding a `/` and appending the `vhost`
The default AMQPConfig has the `vhost` set to `/` which means that if we try to build the uri it will have a double `/`
Moreover if the `vhost` is set to an empty value, the `toUri` method will also fail since we would end up with `/?heartbeat...`

I believe we should be checking the `vhost` value and setting it to an empty string if the we receive `/` as the vhost
Regarding the uri building, we should not be forcing a `/` after the `port` as this will fail to build the amqp connection

**Comment by svroonland** [comment]
Agreed. Would you be willing to submit a PR?
